### ISSUE TITLE
Large.index and reddit.db : No such files or directory

### ISSUE THREAD

**Issue by hinaghafoor** [JRC1995/Chatbot#2]
Hello sir,
can you please tell me from where these files to be downloaded?

**Comment by JRC1995** [comment]
The instructions are here: https://github.com/JRC1995/Chatbot#component--2-retrieval-module
As for the csv files and stuff, I emailed them to you.

**Comment by hinaghafoor** [comment]
thank you

**Comment by PratikGarai** [comment]
Hello sir, 
May I know where the csv files are located?
