### ISSUE TITLE
ConveRT is no longer public

### ISSUE THREAD

**Issue by riju-stone** [JRC1995/Chatbot#5]
I hope the sentence encoder will function without the ConveRT module since it's no longer available on public domains. I'd have to make some modifications to the encoder scripts. Although, I understand it won't be as good as the one using ConveRT but still try it out and see...

**Comment by JRC1995** [comment]
Thank you for notifying. The model uses a concatenation of ConveRT and USE. So the simplest modification would be to remove the ConveRT encodings from the concatenation and just directly use USE.
You probably have to remove traces of ConveRT from everywhere here: https://github.com/JRC1995/Chatbot/search?p=1&q=ConvRT

**Comment by riju-stone** [comment]
Just out of curiosity, can I use any other encoders along with USE to get the desired or even better results?  I don't know much about the latest encoders. If you could suggest some, I could try and implement them into the module...

**Comment by JRC1995** [comment]
Potentially. But I haven't kept up with research in this area. You can
check for papers citing the ConveRT paper in google scholar and see if
anyone has released weights. You can also look into sentence BERT and newer
citations of it.

**Comment by riju-stone** [comment]
Thanks a lot! I'll definitely look into it 😁

**Comment by wu9tiger** [comment]
How do you do that? I got:

File "Chatbot/Scripted/Subscripts/process_pkl.py", line 37, in process
    embedded_bot_queries = encode(sess,bot_queries,bot_contexts,USE_model)
TypeError: encode() missing 1 required positional argument: 'ConvRT_model'

**Comment by JRC1995** [comment]
You have to modify the encoder so that ConvRT is no longer a required argument and so that it is no longer used (following the 2nd comment).

**Comment by wu9tiger** [comment]
Thanks. I did but just noticed that I only modified the fast encoder not the normal encoder which is why it failed.
