### ISSUE TITLE
Reddit Data csv

### ISSUE THREAD

**Issue by riju-stone** [JRC1995/Chatbot#6]
Is there any way I could get access to the Reddit data CSV files used here? I tried google big query but after three queries my quota limit exceeded and on top of that, google cloud is not accepting my card for 60 days trial.

It would really help me if you could upload the csv files to drive or somewhere and share them. It would mean a lot. Thanks a lot in advance...

**Comment by JRC1995** [comment]
I think pushio shares the archives for comments and threads. So you can potentially make csv from those. Also I think there was someone sharing the data somewhere but I don't remember the link.

**Comment by riju-stone** [comment]
Thanks a lot for sending me the files. I will be able to make it work now I guess XD

**Comment by HelloIshHere** [comment]
Just wondering Could you also Send me the files, I can't get them off pullshift.io. I need the Reddit DataCSV files too please.

**Comment by JRC1995** [comment]
Can you share an email address?

**Comment by HelloIshHere** [comment]
bestnotesyoucanbuy@gmail.com

**Comment by HelloIshHere** [comment]
Thanks by the way

**Comment by wu9tiger** [comment]
I would appreciate it if you can send me csv file too: viasat.voice@gmail.com

**Comment by PratikGarai** [comment]
I would appreciate it if you can send me csv file too: pratikgarai0208@gmail.com
